name = "graphql-cdn"
account_id = ""
workers_dev = true
compatibility_date = "2021-11-15"
compatibility_flags = ["streams_enable_constructors"]
main = "./dist/worker.mjs"

[build]
command = "pnpm build"

[durable_objects]
bindings = []
